spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
  datasource:
    password: '150730'
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    url: jdbc:mariadb://192.168.0.8:3306/forms_impac
server:
  port: '8080'
springdoc:
  swagger-ui:
    path: /swagger-ui.html