spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update   
  datasource:
    password: '1234'
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    url: jdbc:mariadb://localhost:3307/diagnostic_form
server:
  port: '8080'
springdoc:
  swagger-ui:
    path: /swagger-ui.html